name: CI

on: [push]

jobs:

  example-1:
    name: Ex1
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.7
          activate-environment: mytest
          environment-file: ../source/environment.yml
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: clone dependency repo
      run: |
        cd ..
        git clone https://github.com/zerpiko/libraries.git
    - name: build
      run: |
        ls ../
        echo $GITHUB_WORKSPACE
        export GITHOME=$GITHUB_WORKSPACE/../
        cd build
        cmake ../source
        make
